services:
  - type: web
    name: bangla-yolo-flask
    runtime: python
    pythonVersion: 3.10.12
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
