services:
  - type: web
    name: bangla-yolo-flask
    env: python
    plan: free
    pythonVersion: 3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      PYTHON_VERSION: 3.10
